#!/usr/bin/env bash

bwrap \
    --ro-bind /nix/store /nix/store \
    --ro-bind /run/current-system/sw /run/current-system/sw \
    --ro-bind /etc/fonts /etc/fonts \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --ro-bind /etc/ssl /etc/ssl \
    --ro-bind /etc/static/ssl /etc/static/ssl \
    --dir /run/user/"$(id -u)" \
    --ro-bind /run/user/"$(id -u)"/bus /run/user/"$(id -u)"/bus \
    --ro-bind /run/user/"$(id -u)"/wayland-1 /run/user/"$(id -u)"/wayland-1 \
    --dev /dev \
    --dev-bind /dev/dri /dev/dri \
    --proc /proc \
    --tmpfs /tmp \
    --bind /home/joachim/.thunderbird /home/joachim/.thunderbird \
    --bind /home/joachim/.config/gtk-3.0/settings.ini /home/joachim/.config/gtk-3.0/settings.ini \
    --bind /home/joachim/.config/dconf/user /home/joachim/.config/dconf/user \
    --bind /home/joachim/Downloads /home/joachim/Downloads \
    --setenv HOME /home/joachim \
    --setenv PATH /run/current-system/sw/bin \
    --hostname RESTRICTED \
    --unshare-all \
    --share-net \
    --new-session \
    thunderbird $@
